// src/lib/pdf.ts
import { jsPDF } from "jspdf";
import "jspdf-autotable";

interface LetterData {
  senderName: string;
  senderAddress: string;
  senderEmail?: string;
  senderPhone?: string;
  recipientName: string;
  recipientAddress: string;
  date: string;
  subject: string;
  body: string;
  statutes: { name: string; article: string; description: string }[];
}

export function generateDemandLetterPDF(data: LetterData) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  let cursorY = 20;

  // ── Header (LEGAL NOTICE) ──
  doc.setFillColor(30, 34, 48); // Dark background for header
  doc.rect(0, 0, pageWidth, 40, "F");
  doc.setTextColor(200, 169, 110); // Gold text
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.text("LEGAL NOTICE", pageWidth / 2, 25, { align: "center" });
  doc.setFontSize(10);
  doc.text("FORMAL DEMAND FOR RESOLUTION", pageWidth / 2, 33, { align: "center" });

  cursorY = 55;
  doc.setTextColor(0, 0, 0); // Reset to black

  // ── Sender Information ──
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.text("FROM (SENDER):", margin, cursorY);
  cursorY += 6;
  doc.setFont("helvetica", "bold");
  doc.text(data.senderName, margin, cursorY);
  cursorY += 5;
  doc.setFont("helvetica", "normal");
  if (data.senderEmail) {
    doc.text(`Email: ${data.senderEmail}`, margin, cursorY);
    cursorY += 5;
  }
  if (data.senderPhone) {
    doc.text(`Phone: ${data.senderPhone}`, margin, cursorY);
    cursorY += 5;
  }
  const senderAddrLines = doc.splitTextToSize(data.senderAddress, 80);
  doc.text(senderAddrLines, margin, cursorY);
  cursorY += Math.max(senderAddrLines.length * 5 + 10, 20);

  const topSectionEnd = cursorY;

  // ── Date & Reference (Right Aligned) ──
  cursorY = 55;
  doc.setFont("helvetica", "bold");
  doc.text("DATE:", pageWidth - margin - 40, cursorY);
  doc.setFont("helvetica", "normal");
  doc.text(data.date, pageWidth - margin, cursorY, { align: "right" });
  cursorY += 10;
  doc.setFont("helvetica", "bold");
  doc.text("REF:", pageWidth - margin - 40, cursorY);
  doc.setFont("helvetica", "normal");
  doc.text(`ACRLE-BD-${Math.floor(Math.random() * 10000)}`, pageWidth - margin, cursorY, { align: "right" });

  cursorY = Math.max(topSectionEnd, cursorY + 15);

  // ── Recipient Information ──
  doc.setFont("helvetica", "bold");
  doc.text("TO (RECIPIENT):", margin, cursorY);
  cursorY += 6;
  doc.text(data.recipientName, margin, cursorY);
  cursorY += 5;
  doc.setFont("helvetica", "normal");
  const recipientAddrLines = doc.splitTextToSize(data.recipientAddress, 80);
  doc.text(recipientAddrLines, margin, cursorY);
  cursorY += recipientAddrLines.length * 5 + 15;

  // ── Subject ──
  doc.setLineWidth(0.5);
  doc.line(margin, cursorY - 5, pageWidth - margin, cursorY - 5);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  const subjectLines = doc.splitTextToSize(`SUBJECT: ${data.subject.toUpperCase()}`, pageWidth - 2 * margin);
  doc.text(subjectLines, margin, cursorY);
  cursorY += subjectLines.length * 6 + 5;
  doc.line(margin, cursorY - 2, pageWidth - margin, cursorY - 2);
  cursorY += 10;

  // ── Salutation ──
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text(`To the Management of ${data.recipientName},`, margin, cursorY);
  cursorY += 10;

  // ── Body ──
  const bodyLines = doc.splitTextToSize(data.body, pageWidth - 2 * margin);
  doc.text(bodyLines, margin, cursorY);
  cursorY += bodyLines.length * 6 + 10;

  // ── Statutes Table ──
  if (data.statutes && data.statutes.length > 0) {
    doc.setFont("helvetica", "bold");
    doc.text("Applicable Legal Statutes & Provisions:", margin, cursorY);
    cursorY += 7;

    (doc as any).autoTable({
      startY: cursorY,
      margin: { left: margin, right: margin },
      head: [["Statute / Law", "Article/Section", "Legal Application"]],
      body: data.statutes.map((s) => [s.name, s.article, s.description]),
      theme: "striped",
      headStyles: { fillStyle: "#1e2230", textColor: [200, 169, 110] }, // Gold theme colors
      styles: { fontSize: 8, cellPadding: 3 },
      columnStyles: {
        0: { cellWidth: 50 },
        1: { cellWidth: 40 },
        2: { cellWidth: "auto" },
      },
    });

    cursorY = (doc as any).lastAutoTable.finalY + 15;
  }

  // ── Closing ──
  if (cursorY > 250) {
    doc.addPage();
    cursorY = 20;
  }
  doc.text("Sincerely,", margin, cursorY);
  cursorY += 10;
  doc.setFont("helvetica", "bold");
  doc.text(data.senderName, margin, cursorY);

  // ── Footer ──
  const totalPages = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(
      `Page ${i} of ${totalPages} — Generated by ACRLE (Autonomous Consumer Rights & Legal Recovery Engine)`,
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: "center" }
    );
  }

  return doc;
}
